development:
  adapter: postgresql
  encoding: unicode
  database: got_fixed_demo_development
  pool: 5
  username: got_fixed_demo
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: got_fixed_demo_test
  pool: 5
  username: got_fixed_demo
  password:
