# TODO: Update the user_mailer.from attribute with your email address.
user_mailer:
  from: '"GotFixed Demo Notifications" <seb@saunier.me>'
  subject_template: "[Fixed] %{title}"

github:
  - owner: ssaunier
    repo: got_fixed_demo
    labels: public  # Comma-separated labels for github issues to be shown on dashboard
    access_token: <%= ENV['GITHUB_PERSONAL_ACCESS_TOKEN'] %>
    webhook_secret: <%= ENV['GITHUB_WEBHOOK_SECRET'] %>